const currency = '\৳';

enum OrderStatus {
  Pending, Processing, Delivered, Cancelled, Returned
}

final cities = [
  'Dhaka',
  'Chittagong',
  'Khulna',
  'Rajshahi',
  'Sylhet',
  'Barisal',
  'Rangpur',
  'Comilla',
  'Narayanganj',
  'Gazipur',
  'Mymensingh',
  'Dinajpur',
  'Jessore',
  'Bogra',
  'Tangail',
  'Pabna',
  'Thakurgaon',
  'Kushtia',
  'Saidpur',
  'Brahmanbaria',
  'Faridpur',
  'Cox\'s Bazar',
  'Bagerhat',
  'Narsingdi',
  'Satkhira',
  'Feni',
  'Joypurhat',
  'Chapai Nawabganj',
  'Natore',
  'Sirajganj',
  'Netrokona',
  'Magura',
  'Sherpur',
  'Lakshmipur',
  'Naogaon',
  'Jhenaidah',
  'Chuadanga',
  'Habiganj',
  'Sunamganj',
  'Gaibandha',
  'Lalmonirhat',
  'Nilphamari',
  'Pirojpur',
  'Bandarban',
  'Khagrachhari',
  'Rangamati',
  'Barguna',
  'Patuakhali',
  'Bhola',
  'Jhalokati',
  'Madaripur',
  'Gopalganj',
  'Manikganj',
  'Munshiganj',
  'Shariatpur',
  'Rajbari',
  'Meherpur',
  'Norail',
  'Panchagarh',
  'Kurigram'
];
